package optimisation

import (
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/assignment"
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/plan"
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/workitem"
)

// simulatedAnnealingAlgorithm implements Algorithm using a deterministic
// simulated annealing approach.
//
// It explores beyond strictly improving moves during the "hot" phase,
// then converges toward the best solution during the "cold" phase.
// This implementation is deterministic — no randomness is involved.
type simulatedAnnealingAlgorithm struct{}

const maxIterations = 100

func init() {
	register(&simulatedAnnealingAlgorithm{})
}

func (sa *simulatedAnnealingAlgorithm) Name() string {
	return "simulated-annealing"
}

// Solve starts from the constructive solution and iterates through candidate
// moves generated by the neighbourhood.
//
// During the hot phase (first half of iterations), the algorithm accepts the
// first valid move found — regardless of whether it improves the score.
// During the cold phase (second half), only improving moves are accepted.
//
// This proves the platform can host algorithms with non-greedy acceptance
// policies while remaining deterministic.
func (sa *simulatedAnnealingAlgorithm) Solve(items []workitem.WorkItem, capacities []ResourceCapacity, priorities []WorkItemPriority) (plan.OptimisedPlan, error) {
	if err := validate(items, capacities); err != nil {
		return plan.OptimisedPlan{}, err
	}

	// Start from the constructive solution.
	sorted := orderByPriority(items, priorities)
	assignments, unassigned := assignItems(sorted, capacities, priorities)

	// Build lookups.
	requiredSkillOf := make(map[string]string, len(priorities))
	for _, p := range priorities {
		requiredSkillOf[p.WorkItemID] = p.RequiredSkill
	}

	resourceIndex := make(map[string]int, len(capacities))
	for i, rc := range capacities {
		resourceIndex[rc.ResourceID] = i
	}

	totalItems := len(items)
	bestAssignments := copyAssignments(assignments)
	bestUnassigned := copyStrings(unassigned)
	bestScore := calculateScore(len(bestAssignments), totalItems)

	for iteration := 0; iteration < maxIterations; iteration++ {
		if len(unassigned) == 0 {
			break // nothing left to improve
		}

		hot := iteration < maxIterations/2
		moved := false

		for ui := 0; ui < len(unassigned); ui++ {
			unassignedID := unassigned[ui]
			requiredSkill := requiredSkillOf[unassignedID]

			moves := GenerateMoves(unassignedID, requiredSkill, assignments, capacities, resourceIndex, requiredSkillOf)

			for _, m := range moves {
				newAssignments, ok := ApplyMove(m, assignments)
				if !ok {
					continue
				}

				newScore := calculateScore(len(newAssignments), totalItems)

				if newScore > bestScore || hot {
					assignments = newAssignments
					unassigned = append(unassigned[:ui], unassigned[ui+1:]...)

					if newScore > bestScore {
						bestAssignments = copyAssignments(assignments)
						bestUnassigned = copyStrings(unassigned)
						bestScore = newScore
					}

					moved = true
					break
				}
			}

			if moved {
				break
			}
		}

		if !moved {
			break // no valid moves found
		}
	}

	// Return the best solution found.
	return buildResult(bestAssignments, bestUnassigned, totalItems, capacities)
}

// copyAssignments returns a copy of the assignments slice.
func copyAssignments(src []assignment.Assignment) []assignment.Assignment {
	cp := make([]assignment.Assignment, len(src))
	copy(cp, src)
	return cp
}

// copyStrings returns a copy of a string slice.
func copyStrings(src []string) []string {
	cp := make([]string, len(src))
	copy(cp, src)
	return cp
}
