package optimisation

import (
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/assignment"
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/plan"
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/workitem"
)

// simulatedAnnealingAlgorithm implements Algorithm using a deterministic
// simulated annealing approach.
type simulatedAnnealingAlgorithm struct{}

const maxIterations = 100

func init() {
	register(&simulatedAnnealingAlgorithm{})
}

func (sa *simulatedAnnealingAlgorithm) Name() string {
	return "simulated-annealing"
}

// Solve starts from the constructive solution and iterates through candidate
// moves generated by the neighbourhood (placement and swap moves).
//
// During the hot phase (first half of iterations), the algorithm accepts the
// first valid move found — regardless of whether it improves the score.
// During the cold phase (second half), only improving moves are accepted.
func (sa *simulatedAnnealingAlgorithm) Solve(items []workitem.WorkItem, capacities []ResourceCapacity, priorities []WorkItemPriority) (plan.OptimisedPlan, error) {
	if err := validate(items, capacities); err != nil {
		return plan.OptimisedPlan{}, err
	}

	sorted := orderByPriority(items, priorities)
	assignments, unassigned := assignItems(sorted, capacities, priorities)

	requiredSkillOf := make(map[string]string, len(priorities))
	for _, p := range priorities {
		requiredSkillOf[p.WorkItemID] = p.RequiredSkill
	}

	resourceIndex := make(map[string]int, len(capacities))
	for i, rc := range capacities {
		resourceIndex[rc.ResourceID] = i
	}

	totalItems := len(items)
	bestAssignments := copyAssignments(assignments)
	bestUnassigned := copyStrings(unassigned)
	bestScore := calculateScore(len(bestAssignments), totalItems)

	for iteration := 0; iteration < maxIterations; iteration++ {
		hot := iteration < maxIterations/2
		moved := false

		// Try placement moves for unassigned items.
		for ui := 0; ui < len(unassigned); ui++ {
			unassignedID := unassigned[ui]
			requiredSkill := requiredSkillOf[unassignedID]

			moves := GenerateMoves(unassignedID, requiredSkill, assignments, capacities, resourceIndex, requiredSkillOf)

			for _, m := range moves {
				newAssignments, ok := ApplyMove(m, assignments)
				if !ok {
					continue
				}

				newScore := calculateScore(len(newAssignments), totalItems)

				if newScore > bestScore || hot {
					assignments = newAssignments
					unassigned = append(unassigned[:ui], unassigned[ui+1:]...)

					if newScore > bestScore {
						bestAssignments = copyAssignments(assignments)
						bestUnassigned = copyStrings(unassigned)
						bestScore = newScore
					}

					moved = true
					break
				}
			}

			if moved {
				break
			}
		}

		if moved {
			continue
		}

		// Try swap moves.
		swaps := GenerateSwapMoves(assignments, capacities, resourceIndex, requiredSkillOf)
		for _, swap := range swaps {
			newAssignments, ok := ApplyMove(swap, copyAssignments(assignments))
			if !ok {
				continue
			}

			newScore := calculateScore(len(newAssignments), totalItems)

			if newScore > bestScore || hot {
				assignments = newAssignments

				if newScore > bestScore {
					bestAssignments = copyAssignments(assignments)
					bestUnassigned = copyStrings(unassigned)
					bestScore = newScore
				}

				moved = true
				break
			}
		}

		if !moved {
			break
		}
	}

	return buildResult(bestAssignments, bestUnassigned, totalItems, capacities)
}

// copyAssignments returns a copy of the assignments slice.
func copyAssignments(src []assignment.Assignment) []assignment.Assignment {
	cp := make([]assignment.Assignment, len(src))
	copy(cp, src)
	return cp
}

// copyStrings returns a copy of a string slice.
func copyStrings(src []string) []string {
	cp := make([]string, len(src))
	copy(cp, src)
	return cp
}
