package optimisation

import (
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/assignment"
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/plan"
	"github.com/timdodgson/open-workforce-platform/platform/go/internal/domain/workitem"
)

// SolveHillClimbing starts from the constructive solution and attempts to
// improve it by exploring neighbouring assignment plans.
//
// A neighbour is generated by moving one assigned Work Item from its current
// Resource to another valid Resource. If a move frees up a slot that allows
// an unassigned item to be placed, the score improves.
//
// The algorithm stops when no improving neighbour can be found.
// It is deterministic — no randomness is involved.
func SolveHillClimbing(items []workitem.WorkItem, capacities []ResourceCapacity, priorities []WorkItemPriority) (plan.OptimisedPlan, error) {
	if err := validate(items, capacities); err != nil {
		return plan.OptimisedPlan{}, err
	}

	// Start from the constructive solution.
	sorted := orderByPriority(items, priorities)
	assignments, unassigned := assignItems(sorted, capacities, priorities)

	// Build required skill lookup.
	requiredSkillOf := make(map[string]string, len(priorities))
	for _, p := range priorities {
		requiredSkillOf[p.WorkItemID] = p.RequiredSkill
	}

	// Build resource index lookup.
	resourceIndex := make(map[string]int, len(capacities))
	for i, rc := range capacities {
		resourceIndex[rc.ResourceID] = i
	}

	// Hill climbing loop.
	improved := true
	for improved {
		improved = false

		// Try to place each unassigned item by moving an existing assignment.
		for ui := 0; ui < len(unassigned); ui++ {
			unassignedID := unassigned[ui]
			requiredSkill := requiredSkillOf[unassignedID]

			if placed := tryPlace(unassignedID, requiredSkill, &assignments, capacities, resourceIndex, requiredSkillOf); placed {
				// Remove from unassigned.
				unassigned = append(unassigned[:ui], unassigned[ui+1:]...)
				improved = true
				break // restart search from the top
			}
		}
	}

	return buildResult(assignments, unassigned, len(items), capacities)
}

// tryPlace attempts to place an unassigned work item by finding a resource that
// could accept it if an existing item on that resource were moved elsewhere.
//
// Returns true if placement succeeded (assignments slice is mutated in place).
func tryPlace(
	workItemID string,
	requiredSkill string,
	assignments *[]assignment.Assignment,
	capacities []ResourceCapacity,
	resourceIndex map[string]int,
	requiredSkillOf map[string]string,
) bool {
	// First, try direct placement (resource has capacity without any moves).
	remaining := computeRemaining(*assignments, capacities, resourceIndex)
	for i, rc := range capacities {
		if canAccept(rc, remaining[i], requiredSkill) {
			a, err := assignment.New(rc.ResourceID, workItemID)
			if err != nil {
				continue
			}
			*assignments = append(*assignments, a)
			return true
		}
	}

	// Try moving an existing assignment to free a slot.
	for ai, existing := range *assignments {
		srcIdx := resourceIndex[existing.ResourceID()]
		srcRC := capacities[srcIdx]

		// Check if the source resource could accept our unassigned item
		// (right skill, available) but is full.
		if !srcRC.Available {
			continue
		}
		if requiredSkill != "" && !hasSkill(srcRC.Skills, requiredSkill) {
			continue
		}

		// Source has the right skill but is full. Try to move the existing item elsewhere.
		existingSkill := requiredSkillOf[existing.WorkItemID()]

		for di, destRC := range capacities {
			if di == srcIdx {
				continue
			}
			destRemaining := remaining[di]
			if canAccept(destRC, destRemaining, existingSkill) {
				// Move existing item from src to dest.
				moved, err := assignment.New(destRC.ResourceID, existing.WorkItemID())
				if err != nil {
					continue
				}
				(*assignments)[ai] = moved

				// Place unassigned item on src (now has a free slot).
				placed, err := assignment.New(srcRC.ResourceID, workItemID)
				if err != nil {
					// Revert move.
					(*assignments)[ai] = existing
					continue
				}
				*assignments = append(*assignments, placed)
				return true
			}
		}
	}

	return false
}

// computeRemaining calculates remaining capacity per resource given current assignments.
func computeRemaining(assignments []assignment.Assignment, capacities []ResourceCapacity, resourceIndex map[string]int) []int {
	remaining := make([]int, len(capacities))
	for i, rc := range capacities {
		remaining[i] = rc.Capacity
	}
	for _, a := range assignments {
		if idx, ok := resourceIndex[a.ResourceID()]; ok {
			remaining[idx]--
		}
	}
	return remaining
}
